### ISSUE TITLE
程序崩了，原因：{err}

### ISSUE THREAD

**Issue by AnmoWu** [Shapooo/WeiBack#3]
在备份我的收藏时出错，使用他人发布并设置相同参数下载成功。如图：
![image](https://github.com/Shapooo/WeiBack/assets/73103395/151c4b4f-1d4a-4e3b-b054-206fb0607744)

**Comment by AnmoWu** [comment]
开始可以加载3-5页，然后程序会崩溃。如果从更后面的位置开始下载，比如下载范围定为220至246页，那么成功加载的页数会缩至1-3页，但最终都会崩溃。

**Comment by Shapooo** [comment]
你好，浏览器按 f12 控制台可以看到更多的错误信息，可以的话把这个信息提供给我方便我定位问题。


> 开始可以加载3-5页，然后程序会崩溃。如果从更后面的位置开始下载，比如下载范围定为220至246页，那么成功加载的页数会缩至1-3页，但最终都会崩溃。

**Comment by AnmoWu** [comment]
好的，以下是错误消息的截图：

![屏幕截图 2023-07-03](https://github.com/Shapooo/WeiBack/assets/73103395/fecf8cfb-fcdf-4c60-8f6c-138b5b8a7372)

不知道这个符不符合你的需求。

**Comment by Shapooo** [comment]
> 好的，以下是错误消息的截图：
> 
> ![屏幕截图 2023-07-03](https://user-images.githubusercontent.com/73103395/250591004-fecf8cfb-fcdf-4c60-8f6c-138b5b8a7372.png)
> 
> 不知道这个符不符合你的需求。

好的，谢谢你的协助。
微博返回的的 json 里有些字段有，有些字段没有，但我并不知道哪些一定有哪些可能没有。有个用户没有高清头像，但我保存的微博里没有出现这个问题所以没有意识到。
我会抽时间修复。
